const Story = () => {
    return (
        <div id="story" className="bg-fixed bg-cover bg-center" style={{ backgroundColor: '#6FDDF6' }}>
            <div className="container mx-auto min-h-screen py-36 w-3/4 md:w-2/3">
                <div className="text-3xl font-bold">Story</div>
                
                <div className="text-xl my-4">The Quest for the Popcorn Bowl – A Tale of Racconius Caesar</div>
                
                <div className="column-1 md:column-3 xl:column-3 column-gap-12 text-sm overflow-x-auto" style={{height: "55vh"}}>
                    <div className="pb-4">It seemed like any other day in the alley. The trash damp, the cans cozy, and every inch of it covered in shadows. You could hear the usual traffic and see the thin strip of sky between the towering buildings. Just like any other day. But for Racconius Caesar this was a day to be remembered; to be scrawled out in graffiti on the alley wall. </div>
                    <div className="pb-4">Today was his day. </div>
                    <div className="pb-4">Today he retrieved the legendary Popcorn Bowl.</div>
                    <div className="pb-4">To be honest, he wasn’t entirely sure what Popcorn was. But he’d seen those tasty nuggets tossed around like fluffy packing peanuts, found their golden kernels buttery and smooth – a fraction of the pleasure the Popcorn itself must hold – and had yearned for them from his throne in the Great Green Dumpster. A worthy prize lesser kings may have been distracted by.</div>
                    <div className="pb-4">Bottom floor. Second window on the right. That’s where it lay: the true prize, the Popcorn Bowl. They left their blinds open and Racconius watched them day after day, night after night. Yet, even to them – the great Hoomans – the Popcorn Bowl was sacred; only brought out on days when they were all gathered. Then, a ritual would begin, and they would summon visions from the gods onto a mirrored screen. Visions he deserved.</div>
                    <div className="pb-4">Racconius had one such screen. It sat on a pile of trash partway down the alley covered in a tarp. He had fought hard for that screen, defending it from others who would call themselves king and steal his treasures. He gingerly lifted a paw, his finger tracing the scar over his left eye. He’d sacrificed much. Yet, no matter how hard he pled, the gods would not hear his plea and the screen remained dark. He needed the Popcorn Bowl. Many of the others had told him he had enough: a dumpster, a holy screen, an alley to command. It was hubris to ask for more. Arrogance. Racconius called it destiny.</div>
                    <div className="pb-4">“Trash Brigade!” Racconius yelled, his voice shrill yet commanding.</div>
                    <div className="pb-4">Three raccoons stumbled out from their various hiding places in the alley. Spike, Lazy Eye, and Diver. Spike, his captain, was named after the spiked collar she wore, though she had also managed to dye part of her fur a vibrant pink with a bottle of pink liquid found in the dumpster. Recently she’d found more and was in the habit of spiking it as well. Lazy Eye was a big raccoon with an eye that only opened halfway and never seemed to look the right way. He wore the discarded t-shirt of a young hooman. It bore the image of a reptile on two legs with arms much too short to be useful; likely hoping to bring awareness to the pitiful creature. Diver was wiry and thin. His fur matted and strewn with bits of garbage from his recent ventures into the local dumpsters. A slightly crazed look in his eyes, he fidgeted with a set of keys he’d found recently. He always seemed to have something new to fiddle with. Together they formed Racconius’s Trash Brigade. All together now, Racconius stood, addressing his subjects.</div>
                    <div className="pb-4">“The Hoomans have made a terrible mistake,” Racconius began, walking along the edge of the Great Green Dumpster. His dumpster. “After a personal message from the gods to one of the younger of the Hoomans, they abandoned the holy Popcorn Bowl on a side table.”</div>
                    <div className="pb-4">Racconius lifted a finger pointing through the window and at the Popcorn Bowl that sat alone beside their large blue throne. Lazy Eye followed his finger and ended his one-eyed gaze staring at the wall beneath the window.</div>
                    <div className="pb-4">“I don’t see anything,” Lazy Eye said.</div>
                    <div className="pb-4">“Farther up,” Racconius said, exasperated.</div>
                    <div className="pb-4">“Oh, haha, I understand,” Lazy Eye said, his laughs lifting his whole body in a few large chuckles.</div>
                    <div className="pb-4">“What was it about?” Diver asked, looking up from the keys.</div>
                    <div className="pb-4">“What was what about?” Racconius replied, his tone growing agitated.</div>
                    <div className="pb-4">“The vision?”</div>
                    <div className="pb-4">Racconius pursed his lips. Lazy Eye could be dismissed but Diver was keener. The young hooman female had received a vision of flying horses (lesser beings) and rainbows. Racconius didn’t know what it meant. In fact, many of the visions the Hoomans received baffled Racconius. He determined they must be personalized to those involved in the ritual. Which was why he needed it for himself, so he could receive the messages the Gods meant for him.</div>
                    <div className="pb-4">Racconius turned his attention back to Diver who looked at him expectantly. Even Spike seemed to have her interest piqued. They would not understand nor accept such lofty aspirations. And he needed their help. He glared at Diver then smiled.</div>
                    <div className="pb-4">“A bounty of food will soon arrive there,” Racconius said, his smile growing wide.</div>
                    <div className="pb-4">It didn’t matter if it wasn’t true, once he had the Popcorn Bowl all of their troubles would be erased.</div>
                    <div className="pb-4">“Now onto assignments,” Racconius said. He lifted a finger at Diver, “You will be the distraction. Infiltrate the building and scrape at the door. Once the female leader of the den answers we will strike from our side.”</div>
                    <div className="pb-4">Diver nodded. Racconius turned to Spike.</div>
                    <div className="pb-4">“Captain Spike your job is to open the window.”</div>
                    <div className="pb-4">“Yes, sir, I’ve been practicing,” Spike said as she pantomimed inching her fingers under an imaginary window.</div>
                    <div className="pb-4">“Good.”</div>
                    <div className="pb-4">Racconius jumped down from the dumpster edge and onto the pavement below, landing on all fours. He moved with purpose towards the waiting window. </div>
                    <div className="pb-4">“Wait, sir,” Racconius turned around and saw Lazy Eye looking at him with his good eye, “what about me? What’s my job?”</div>
                    <div className="pb-4">“You get the pleasure of being our ladder,” Racconius said and pointed to the wall directly beneath the window.</div>
                    <div className="pb-4">“Oh, that sounds important,” Lazy Eye said, his good eye growing large.</div>
                    <div className="pb-4">“Yes, it is,” Racconius smiled at Lazy Eye. To be truthful he was probably his favorite of the three raccoons. Obedient, chipper, grateful, and a bit dim. The epitome of any loyal citizen. “Positions.”</div>
                    <div className="pb-4">Diver nodded again then scurried down the alley to the corner, peeked around either side, then moved out of view.</div>
                    <div className="pb-4">Lazy Eye ran beneath the windows ledge and lifted his paws above his head. Spike climbed onto him then placed her paws on the ledge above.</div>
                    <div className="pb-4">“Wait for the signal,” Racconius said, holding up a warding finger to Spike. She nodded then stayed silent underneath the sill. Racconius listened through the wall. Heard the familiar thuds of footfalls. The creak of a door. Then the expected signal.</div>
                    <div className="pb-4">“AAAAHHHH!!!!” the women screamed, “Vermin!!!”</div>
                    <div className="pb-4">There was the panicked thudding of running feet and Racconius looked up at Spike and nodded. She pulled herself up to the windowsill and with a scrape the window opened. She hopped back down to the street and saluted Racconius.</div>
                    <div className="pb-4">“All done sir.”</div>
                    <div className="pb-4">Racconius returned an appreciative nod then climbed onto Lazy Eye’s paws and up to the sill above. The window hung open and the smell of cinnamon and bread wafted from the den. The smell captivated him for a moment; but he shook his head, throwing off the stupor. Mustn’t be distracted. His eyes locked onto the Popcorn Bowl. He lifted an ear to listen.</div>
                    <div className="pb-4">“I’m telling you, Roger, I saw a raccoon; and if you’re not going to do something about it, I’ll call the city.”</div>
                    <div className="pb-4">There was the click of a door, and her voice became muffled. Perfect. </div>
                    <div className="pb-4">Racconius jumped down from the ledge and onto the carpet below. It was a thick green rug that spread between his toes, cushioning every movement. It would be nice to simply lay here for a moment. No. Another temptation of the gods to distract the unworthy. He blinked and refocused on the Bowl, leaping up to the side table it sat on.</div>
                    <div className="pb-4">The Bowl was a beautiful, deep red. He stared at it in reverence. To touch it scared him more than he expected. What if I’m not worthy? What if I’m smitten? He banished the doubts from his mind. This was his destiny. He grasped the Bowl in both paws, a euphoric chill running down his spine. He looked inside and saw the Popcorn within. Golden and buttery. A simple taste would be fine.</div>
                    <div className="pb-4">He tentatively grasped one of the Popcorns, lifting it up and inspecting it. Light, like a packing peanut, as he’d expected. He brought it to his nose, breathing in the scent deeply. Then, ever so gently, he placed it on his tongue.</div>
                    <div className="pb-4">Flavor exploded through his being. He’d never tasted something so full. It seemed as if his entire magnificent kingdom was drab in that moment, nothing more than a trash heap. He plunged a greedy paw into the Bowl, eating handfuls at a time. Each one drove him deeper into his mania. More. He needed more!</div>
                    <div className="pb-4">A thud on the floor broke him from his reverie and he looked up to see the female of the den staring at him, her mouth agape, her talking device resting on the ground.</div>
                    <div className="pb-4">Racconius placed the current handful of Popcorn into his mouth slowly, hoping against all odds she had not noticed him. Then she screamed.</div>
                    <div className="pb-4">She grabbed a broom from where it leaned against the wall and came running at him with it upraised. </div>
                    <div className="pb-4">He jumped off the table, narrowly avoiding her swing. It struck the Popcorn Bowl, sending it spinning into the air. Blessed Popcorn rained down from the heavens, scattering their goodness across the floor. Racconius couldn’t help but grab at those closest to him and stuff them in his mouth as he scurried towards the open windowsill. Wait! The Bowl! He looked over his shoulder and could see the Bowl lying upside down on the ground just beside the throne. He’d expected resistance. It was their holy Popcorn Bowl, after all. He turned back towards the woman, arching his back, and hissed.</div>
                    <div className="pb-4">She took a step back, fear in her eyes. Racconius took advantage of the moment and dashed across the room towards his prize. His eyes fell on a stray Popcorn, and he felt his body move in that direction. He clenched his teeth, pulled his body back on track, locked his eyes on the bowl, and resisted his urge to stop and eat each and every Popcorn scattered about. He dodged from side to side, avoiding the sweeping blows of the broom. He rolled forward, closing the last of the distance to the Bowl.</div>
                    <div className="pb-4">His fingers grasped its slick, red surface. He flipped it onto its side, a pile of Popcorn on the ground beside it, and pawed as much as he could into the Bowl. Then he spun around facing the female who stood between him and his destiny.</div>
                    <div className="pb-4">“You will not stop Racconius Caesar!” Racconius yelled. </div>
                    <div className="pb-4">He stood on his back legs, Bowl in his front paws, and ran to the blue throne. He set it down on the cushion and climbed up after it before grasping the Bowl in his paws once more. He heard her gasp as he ran upright across the cushioned seats: a vision of dignity, he was sure. His eyes locked on the open window. He heard an enraged scream from behind him. Don’t look back. His paw stepped onto the side table. A simple look over his shoulder showed the female rearing back. The broom grasped in both hands. He set his eyes on the window. He placed the edge of the Bowl inside his mouth, clamping down. He felt a woosh of air as the broom swung towards him. He leapt. The broom struck the side table with a crack. He flew, Popcorn Bowl in mouth, towards the window. Time suspended in that brief moment. Popcorn hung in the air around him. Even more lay scattered across the floor. The head of the broom spun past him in the air. The female held the broken haft of the weapon, her face in a furious grimace. Her eyes locked onto him. He smiled. I win. </div>
                    <div className="pb-4">He tumbled through the window, and into the Bowl; Popcorn exploding into the air in a shower of paradise. Skidding across the alley cement. He quickly pulled himself out, lifting the Bowl, in his paws and ran.</div>
                    <div className="pb-4">“Run!” Racconius yelled, then seeing Lazy Eye start to climb into the dumpster (immediately behind the apartment) yelled again. “Away from here!”</div>
                    <div className="pb-4">Lazy Eye simply let go of the dumpster and fell onto his back before rolling upright and following Racconius. The other two sprang into action stepping in line with him. They dashed down the alleyway, the female’s screams echoing after them.</div>
                    <div className="pb-4">They hid in a neighboring alley until nightfall watching the large building.  From there, they could see various hoomans trespass into his kingdom to inspect it; first the male from the den, and later some who had traps. As darkness descended, they made their way back to their home.</div>
                    <div className="pb-4">“You did it,” Diver said, his voice showing disbelief.</div>
                    <div className="pb-4">“Of course, I did,” Racconius said, struggling to stifle his own excitement. “Now follow me, for glory.”</div>
                    <div className="pb-4">He approached where he had the black screen hidden. A blue plastic tarp with tears and ripped threading hung over the screen, hiding it from prying eyes. He motioned to Spike who moved to the corner, grabbing it with her teeth and pulled the tarp away. The screen sat on a heap of trash, its inky surface reflecting the alley.</div>
                    <div className="pb-4">Racconius beckoned the others to back away then took a step towards the screen, Popcorn Bowl in hand. He lifted the Popcorn Bowl in offering, bowing his head.</div>
                    <div className="pb-4">Nothing happened.</div>
                    <div className="pb-4">He placed the Bowl in front of the screen. The screen stayed dark. He pushed the Bowl forward touching it against the screen.</div>
                    <div className="pb-4">Still nothing.</div>
                    <div className="pb-4">What is going on? He felt his heart race. Why isn’t it working? I have the Bowl. I have the Popcorn. He attempted various other motions and placements with the Bowl, all without success. Am I not worthy? His eyes fell to his feet, then his hands tightened on the Popcorn Bowl. NO! His eyes darted desperately at his fellow raccoons then back towards the window of the Hoomans. What more do I need! </div>
                    <div className="pb-4">A flickering light came from the window. No, it can’t be. He moved so he could see through the window and saw the visions on the Hooman’s screen. No!</div>
                    <div className="pb-4">He threw the bowl to the side, the popcorn spilling onto the ground: a dismal reminder of his failure. The other three raccoons dove at it, devouring the mana – no, fool’s gold.</div>
                    <div className="pb-4">“Leave me!” he yelled, the others looked up from where they ate, their mouths filled with the golden goodness. The memory of it seemed like ash in his mouth. “Leave!”</div>
                    <div className="pb-4">They scurried away, taking the bowl and popcorn with them. Racconius slumped. He felt a sickening hole in his chest. A deep and empty cavern.</div>
                    <div className="pb-4">He crawled up into his dumpster and nestled into a soft bag of cotton he had scrounged up a week before. He could see through the window from there. </div>
                    <div className="pb-4">How? How did they access this power? His eyes squinted, taking in every detail. He would watch for now. Watch and learn. One day the power would be his. No Hooman or raccoon would stand in his way. Not from his destiny.</div>
                    <div className="pb-4">Maybe the gods had given him a vision after all. </div>
                </div>

            </div>
        </div>
    );
}

export default Story;